version: "3.9"

services:
  vue-app:
    build: .
    container_name: kvantorium
    expose:
      - "80"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=game.cnfro52.ru,www.game.cnfro52.ru
      - LETSENCRYPT_HOST=game.cnfro52.ru,www.game.cnfro52.ru
      - LETSENCRYPT_EMAIL=ilia.shevhenkov@gmail.com
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge
